# Generated by Django 4.0.3 on 2022-03-17 09:21

from django.db import migrations, models
import myclinic.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclinic', '0006_alter_appointment_code_alter_docprofile_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='docprofile',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='docprofile',
            name='edu_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Schedule'),
        ),
    ]
