# Generated by Django 4.0.3 on 2022-03-18 14:20

from django.db import migrations, models
import myclinic.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclinic', '0014_alter_appointment_code_alter_appointment_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Appointment ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='docprofile',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Doctor ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Schedule ID'),
        ),
    ]
