# Generated by Django 4.0.3 on 2022-03-22 08:36

from django.db import migrations, models
import myclinic.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclinic', '0027_delete_employee_alter_appointment_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Employee ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('age', models.DateField()),
                ('image', models.ImageField(upload_to='img/Employee')),
                ('email', models.EmailField(max_length=255)),
                ('joining_date', models.DateField()),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Laboratorist', 'Laboratorist'), ('Pharmacist', 'Pharmacist'), ('Accountant', 'Accountant'), ('Receptionist', 'Receptionist')], max_length=15)),
                ('status', models.CharField(choices=[('A', 'Active'), ('B', 'Inactive')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Appointment ID'),
        ),
        migrations.AlterField(
            model_name='docprofile',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Doctor ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Schedule ID'),
        ),
    ]
