# Generated by Django 4.0.3 on 2022-04-05 10:37

from django.db import migrations, models
import myclinic.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclinic', '0029_alter_appointment_code_alter_docprofile_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Appointment ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Dentists', 'Dentists'), ('Neurology', 'Neurology'), ('Opthamology', 'Opthamology'), ('Orthopedics', 'Orthopedics'), ('Cancer Department', 'Cancer Department'), ('ENT Department', 'ENT Department')], max_length=93),
        ),
        migrations.AlterField(
            model_name='docprofile',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Doctor ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='code',
            field=models.CharField(default=myclinic.models.generate_id_length, editable=False, max_length=7, unique=True, verbose_name='Schedule ID'),
        ),
    ]
